### 授权码模式
### 第一步申请授权码(浏览器请求)
### http://localhost:63070/auth/oauth/authorize?client_id=XcWebApp&response_type=code&scope=all&redirect_uri=http://localhost/
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=VsnGYO&redirect_uri=http://localhost/


### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username=admin&password=111111


### 校验JWT令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjcmVhdGVUaW1lXCI6XCIyMDIyLTA5LTI4VDA4OjMyOjAzXCIsXCJpZFwiOlwiNDhcIixcIm5hbWVcIjpcIuezu-e7n-euoeeQhuWRmFwiLFwic2V4XCI6XCIxXCIsXCJzdGF0dXNcIjpcIjFcIixcInVzZXJuYW1lXCI6XCJhZG1pblwiLFwidXR5cGVcIjpcIjEwMTAwM1wifSIsInNjb3BlIjpbImFsbCJdLCJleHAiOjE2Nzk1NDMzODMsImF1dGhvcml0aWVzIjpbInRlc3QiXSwianRpIjoiZWRkNmI4ZWYtZjNlYS00ZDU1LTg1M2ItZTRkMzU1NjQwNzk4IiwiY2xpZW50X2lkIjoiWGNXZWJBcHAifQ.j0YXQq7M1FD5v8g45EypDcpmemrnMhsdpcjRk9yZrnI


### 密码模式登录
POST {{auth_host}}/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"admin","password":"111111",,"authType":"password"}


###修改密码
POST {{gateway_host}}/auth/findpassword
Content-Type: application/json

{
  "cellphone": "",
  "email": "1606441608@qq.com",
  "checkcodekey": "",
  "checkcode": "BYIch",
  "confirmpwd": "123456",
  "password": "123456"
}


###测试访问
GET {{auth_host}}/auth/r/r4

